name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - "feature/*"

env:
  COMPOSER_FLAGS: --ansi --no-interaction --no-progress --no-suggest --prefer-dist --no-dev

jobs:
  build:
    name: Upload Release Asset

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 5.4
          - 7.4

    steps:
      - name: Get convenient env variables
        uses: FranzDiebold/github-env-vars-action@v1.2.0

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: soap
          ini-values: memory_limit=-1, phar.readonly=Off
          php-version: ${{ matrix.php-version }}

      - name: Display PHP Version
        run: php -v

      - name: Display release name
        run: echo $GITHUB_REF_NAME_SLUG

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies from composer.lock
        run: composer install ${{ env.COMPOSER_FLAGS }}

      - name: Validate composer.json
        run: composer validate

      - name: Install Box2
        run: curl -LSs https://box-project.github.io/box2/installer.php | php

      - name: Build phar file
        run: mkdir bin; php box.phar build

      - name: Display generated wsdltophp version
        run: php bin/wsdltophp.phar --version

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          release_name: ${{ env.GITHUB_REF_NAME }} - PHP ${{ matrix.php-version }}
          draft: true
          body: TODO

      - name: Upload phar to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/wsdltophp.phar
          asset_name: wsdltophp-${{ env.GITHUB_REF_NAME_SLUG }}-${{ matrix.php-version }}.phar
          asset_content_type: application/octet-stream


      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .github/Dockerfile
          build-args: |
            PHP=${{ matrix.php-version }}
            WSDLTOPHP=${{ env.GITHUB_REF_NAME_SLUG }}
            PHAR=./bin/wsdltophp.phar
          tags: mikaelcom/wsdltophp:${{ env.GITHUB_REF_NAME_SLUG }}
